training_data = [["The order came 5 days early", "positive"],
["The item exceeded my expectations", "positive"],
["I ordered more for my friends", "positive"],
["I would buy this again", "positive"],
["I would recommend this to others", "positive"],
["The package was damaged", "negative"],
["The order is 5 days late", "negative"],
["The order was incorrect", "negative"],
["I want to return my item", "negative"],
["The item's material feels low quality", "negative"],
["The product was okay", "neutral"],
["I received five items in total", "neutral"],
["I bought it from the website", "neutral"],
["I used the product this morning", "neutral"],
["The product arrived yesterday", "neutral"],
["The food was excellently cooked", "positive"],
["The food was well cooked", "positive"],
["The food was decently cooked", "neutral"],
["The food was badly cooked", "negative"],
["I could barely contain myself from eating another plate", "positive"],
["The food was barely edible", "negative"],
["I had a wonderful time being served by Tracy", "positive"],
["The environment was very welcoming and staff were friendly", "positive"],
["Overall, the food was alright", "neutral"],
["The environment was dirty and staff were unfriendly", "negative"],
["The restaurant was well decorated", "positive"],
["The restaurant was ugly", "negative"],
["The waittress named May was terribly ill-mannered", "negative"],
["My family is definitely coming back for more", "positive"],
["My family will never be coming back", "negative"],
["I ate the chicken sandwich", "neutral"],
["The owner of this restaurant is careless", "negative"],
["Patricia dropped 3 dishes on the floor", "negative"],
["Bob picked his nose in front of my family", "negative"],
["Bob had a wonderful attitude", "positive"]]